#!/bin/bash

# Taken from ClioPatria, written by Jan Wielemaker.

findexe()
{ oldifs="$IFS"
  IFS=:
  for d in $PATH; do
    if [ -x $d/$1 ]; then
       IFS="$oldifs"
       return 0
    fi
  done
  IFS="$oldifs"
  return 1
}

if [ -z "$SWIPL" ]; then
  for f in swi-prolog swipl; do
    if [ -z "$SWIPL" ] && findexe $f; then
       SWIPL=$f
    fi
  done
fi

if [ -z "$SWIPL" ]; then
  echo "ERROR: Cannot find SWI-Prolog."
  exit 1
fi

run="$(dirname $0)/run.pl"

$SWIPL -q -f "$run" -- $*

